notARepository: "quit"
git:
  overrideGpg: true
os:
  editPreset: nvim
gui:
  showBottomLine: false
  theme:
    activeBorderColor:
      - cyan
    selectedLineBgColor:
      - black
    unstagedChangesColor:
      - yellow
  border: rounded
  nerdFontsVersion: "3"

customCommands:
  - key: "x"
    prompts:
      - type: "input"
        title: "Commit and bypass hooks"
        initialValue: ""
    command: HUSKY=0 git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: yes

  - key: "X"
    description: "Amend last commit and bypass hooks"
    command: "HUSKY=0 git commit --amend --date=now --no-edit"
    context: "global"
    subprocess: yes
