return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  opts = {
    -- Own dir, not site/: TSUpdate errors on any foreign parser it finds in site/parser.
    install_dir = vim.fs.joinpath(vim.fn.stdpath("data"), "nvim-treesitter"),
    ensure_installed = {
      "bash",
      "c",
      "css",
      "devicetree",
      "dockerfile",
      "gitignore",
      "go",
      "graphql",
      "html",
      "javascript",
      "json",
      "json5",
      "lua",
      "markdown",
      "markdown_inline",
      "nix",
      "prisma",
      "query",
      "regex",
      "sql",
      "svelte",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
